### ISSUE TITLE
Decompilation fails on server pipeline

### ISSUE THREAD

**Issue by Pablete1234** [Earthcomputer/jarmod-buildsystem-2#1]
When defining the pipeline=server on the config, patch fails trying to search for an output.zip.

https://i.imgur.com/KfITYUv.png

**Comment by Earthcomputer** [comment]
This is an issue with the extra patches to fix MCPConfig, they only work on the joined pipeline. Either you will have to use joined, or you will have to delete the conf/patches directory and have a few recompile errors. This will be fixed when MCPConfig is fixed.

**Comment by Earthcomputer** [comment]
Should be fixed now.
